name: tika_nissaya
description: Word-to-Word translation of Tika Pali.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.3.0+6

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.1.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.0.5
  enum_to_string: ^2.0.1
  grouped_list: ^6.0.0
  scrollable_positioned_list: ^0.3.8
  path_provider: ^2.0.8
  path: ^1.8.0
  logger: ^2.7.0
  cupertino_icons: ^1.0.2
  # go_router: ^3.1.1
  flutter_widget_from_html_core: ^0.17.2
  sqflite: ^2.1.0
  sqflite_common_ffi: ^2.4.0
  # sqlite3_flutter_libs:
  just_pdf_viewer:
    git:
      url: https://github.com/pndaza/just_pdf_viewer
      ref: main
  app_links: ^7.0.0
  easy_debounce: ^2.0.3
  window_manager: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.1.4
  freezed: ^3.2.5
  build_runner:
  flutter_launcher_icons: ^0.14.4
  msix: ^3.6.2
  icons_launcher: ^2.0.6


icons_launcher:
  image_path: "assets/icon/icon.jpg"
  platforms:
    macos:
      enable: true

msix_config:
  display_name: Tika Nissaya
  identity_name: 38337PnDaza.TikaNissaya
  publisher_display_name: PnDaza
  publisher: CN=D6488D0D-2C1E-4BF6-9E71-85196599EEB3
  msix_version: 1.1.0.0
  protocol_activation: tikanissaya
  store: true
  logo_path: .\assets\icon\icon.jpg

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/database/tika_nsy.db
    - assets/books/cover/
    - assets/books/pdf/
    - assets/info.html

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700